version: "3"

services:

  proxy:
    image: nginx:stable
    networks:
      - nextcloud_network
    container_name: nextcloud-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/salman/nextcloud-compose/data/certs:/etc/nginx/certs
    restart: unless-stopped
  
  nextcloud:
    image: nextcloud:latest
    networks:
      - nextcloud_network
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - /home/salman/nextcloud-disk:/var/www/html
  
  mysql:
    image: mysql:8.0
    networks:
      - nextcloud_network
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  nextcloud:

networks:
  nextcloud_network:    
